name: Build and Deploy user-service
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: Building the user-service app
    runs-on: ubuntu-today #runner: where you want to run this actions
    #each job has different steps
    steps:
      - name: checkout code
        uses: actions/checkout@v3 #uses means that you want to run some actions from gitHub actions marketplace

      - name: setup JDK 17 #setting up jdk17 on the gitHub runner
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file user-service/pom.xml

      - name: Build the app
        run: mvn -B package --file user-service/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: user-service
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: user-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:today







      - name: Unit Tests
        run: mvn -B test --file department-service/pom.xml

      - name: Build the app
        run: mvn -B package --file department-service/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: user-service
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/department-service:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: department-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/department-service:today








      - name: Unit Tests
        run: mvn -B test --file service-registry/pom.xml

      - name: Build the app
        run: mvn -B package --file service-registry/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: service-registry
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/service-registry:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: service-registry
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/service-registry:today




      - name: Unit Tests
        run: mvn -B test --file cloud-gateway/pom.xml

      - name: Build the app
        run: mvn -B package --file cloud-gateway/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: cloud-gateway
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/cloud-gateway:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: cloud-gateway
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cloud-gateway:today





      - name: Unit Tests
        run: mvn -B test --file config-server/pom.xml

      - name: Build the app
        run: mvn -B package --file config-server/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: config-server
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/config-server:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: config-server
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/config-server:today




