name: Build and Deploy user-service
on:
  push:
    branches:
      - master
  workflow_dispatch:




env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: cluster1
  GKE_ZONE: us-central1-c









jobs:
  build:
    name: Building and pushing all the microservices
    runs-on: ubuntu-latest #runner: where you want to run this actions
    #each job has different steps
    steps:
      - name: checkout code
        uses: actions/checkout@v3 #uses means that you want to run some actions from gitHub actions marketplace

      - name: setup JDK 17 #setting up jdk17 on the gitHub runner
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests for user-service
        run: mvn -B test --file user-service/pom.xml

      - name: Build user-service
        run: mvn -B package --file user-service/pom.xml

      - name: Build user-service Docker Image
        uses: docker/build-push-action@v2
        with:
          context: user-service
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push user-service Docker Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: user-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:today







      - name: Unit Tests for department-service
        run: mvn -B test --file department-service/pom.xml

      - name: Build department-service
        run: mvn -B package --file department-service/pom.xml

      - name: Build department-service Docker Image
        uses: docker/build-push-action@v2
        with:
          context: department-service
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/department-service:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push department-service Docker Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: department-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/department-service:today








      - name: Unit Tests for service-registry
        run: mvn -B test --file service-registry/pom.xml

      - name: Build service-registry
        run: mvn -B package --file service-registry/pom.xml

      - name: Build service-registry Docker Image
        uses: docker/build-push-action@v2
        with:
          context: service-registry
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/service-registry:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push service-registry Docker Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: service-registry
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/service-registry:today




      - name: Unit Tests for cloud-gateway
        run: mvn -B test --file cloud-gateway/pom.xml

      - name: Build the app
        run: mvn -B package --file cloud-gateway/pom.xml

      - name: Build cloud-gateway Docker Image
        uses: docker/build-push-action@v2
        with:
          context: cloud-gateway
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/cloud-gateway:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push cloud-gateway Docker Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: cloud-gateway
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cloud-gateway:today





      - name: Unit Tests for config-server
        run: mvn -B test --file config-server/pom.xml

      - name: Build the app
        run: mvn -B package --file config-server/pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: config-server
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/config-server:today

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: config-server
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/config-server:today





  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{env.PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.APPLICATION_CREDENTIALS}} #Google console key, the key for the project: IAM&Admin >service accounts > keys > convert your key to base 64
          CLUSTER_NAME: ${{env.GKE_CLUSTER}}
          ZONE_NAME: ${{env.GKE_ZONE}}

        with:
          args: apply -f K8S/





